//
// **** AUTOMATICALLY GENERATED BY mk-node-decls.pl -- DO NOT EDIT ****
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace m19 {
class evaluation_node; 
class if_else_node; 
class if_node; 
class print_node; 
class program_node; 
class read_node; 
class while_node; 

} // namespace m19

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_m19_NODE_ALLNODES_H__
#define __AUTOMATIC_m19_NODE_ALLNODES_H__

#include "ast/evaluation_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/print_node.h"
#include "ast/program_node.h"
#include "ast/read_node.h"
#include "ast/while_node.h"


#endif /* !defined(__AUTOMATIC_m19_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */
